// export const PRODUCTS = [
//   {
//     id: "10",
//     imageUrl: "/products/ahlam-coffee/ahlam/1.png",
//     title: "Syltherine",
//     description: "Stylish cafe chair",
//     price: "27000",
//     otherPrice: "3.500.000",
//     type: "DISCOUNTED",
//     typeValue: "-30%",
//   },
//   {
//     id: "20",
//     imageUrl: "/products/ahlam-coffee/ahlam/4.png",

//     title: "Leviosa V3",
//     description: "Stylish cafe chair",
//     price: "27000",
//     otherPrice: "3.500.000",
//     type: "DISCOUNTED",
//     typeValue: "-30%",
//   },
//   {
//     id: "30",
//     imageUrl: "/products/ahlam-coffee/ahlam/3.png",
//     title: "Lolito Bilo",
//     description: "Luxury big sofa",
//     price: "500",
//     otherPrice: "14.000.000",
//     type: "DISCOUNTED",
//     typeValue: "-50%",
//   },
//   {
//     id: "40",
//     imageUrl: "/products/ahlam-coffee/ahlam/2.png",

//     title: "Respira Xen",
//     description: "Outdoor bar table and stool",
//     price: "7000",
//     otherPrice: "",
//     type: "NEW",
//     typeValue: "New",
//   },
//   {
//     id: "50",
//     imageUrl: "/products/ahlam-coffee/ahlam/1.png",

//     title: "Grifo Xen",
//     description: "Night lamp",
//     price: "600",
//     otherPrice: "",
//     type: "NORMAL",
//     typeValue: "",
//   },

//   {
//     id: "60",
//     imageUrl: "/products/ahlam-coffee/ahlam/2.png",

//     title: "Muggo Buni",
//     description: "Small mug",
//     price: "4000",
//     otherPrice: "",
//     type: "NEW",
//     typeValue: "New",
//   },
//   {
//     id: "70",
//     imageUrl: "/products/ahlam-coffee/ahlam/1.png",
//     title: "Pingky",
//     description: "Cute bed set",
//     price: "500",
//     otherPrice: "14.000.000",
//     type: "DISCOUNTED",
//     typeValue: "-50%",
//   },

//   {
//     id: "80",
//     imageUrl: "/products/ahlam-coffee/ahlam/3.png",

//     title: "Potty",
//     description: "Minimalist flower pot",
//     price: "7000",
//     otherPrice: "",
//     type: "NEW",
//     typeValue: "New",
//   },
//   {
//     id: "90",
//     imageUrl: "/products/ahlam-coffee/ahlam/2.png",

//     title: "Syltherine v2",
//     description: "Stylish cafe chair",
//     price: "27000",
//     otherPrice: "3.500.000",
//     type: "DISCOUNTED",
//     typeValue: "-30%",
//   },
//   {
//     id: "100",
//     imageUrl: "/products/ahlam-coffee/ahlam/3.png",

//     title: "Leviosa V2",
//     description: "Stylish cafe chair",
//     price: "27000",
//     otherPrice: "3.500.000",
//     type: "DISCOUNTED",
//     typeValue: "-30%",
//   },
//   {
//     id: "110",
//     imageUrl: "/products/ahlam-coffee/ahlam/4.png",

//     title: "Lolito Vilo",
//     description: "Luxury big sofa",
//     price: "500",
//     otherPrice: "14.000.000",
//     type: "DISCOUNTED",
//     typeValue: "-50%",
//   },
//   {
//     id: "120",
//     imageUrl: "/products/ahlam-coffee/ahlam/1.png",

//     title: "Respira Uno",
//     description: "Outdoor bar table and stool",
//     price: "7000",
//     otherPrice: "",
//     type: "NEW",
//     typeValue: "New",
//   },
//   {
//     id: "130",
//     imageUrl: "/products/ahlam-coffee/ahlam/1.png",

//     title: "Grifo Yon",
//     description: "Night lamp",
//     price: "600",
//     otherPrice: "",
//     type: "NORMAL",
//     typeValue: "",
//   },

//   {
//     id: "140",
//     imageUrl: "/products/ahlam-coffee/ahlam/4.png",

//     title: "Muggo Sacpe",
//     description: "Small mug",
//     price: "4000",
//     otherPrice: "",
//     type: "NEW",
//     typeValue: "New",
//   },
//   {
//     id: "150",
//     imageUrl: "/products/ahlam-coffee/ahlam/2.png",

//     title: "Pingky Hoi",
//     description: "Cute bed set",
//     price: "500",
//     otherPrice: "14.000.000",
//     type: "DISCOUNTED",
//     typeValue: "-50%",
//   },

//   {
//     id: "160",
//     imageUrl: "/products/ahlam-coffee/ahlam/3.png",

//     title: "Potty Been",
//     description: "Minimalist flower pot",
//     price: "7000",
//     otherPrice: "",
//     type: "NEW",
//     typeValue: "New",
//   },
// ];

export const PRODUCTS = [
  {
    id: "1",
    imageUrl: "/products/ahlam-coffee/ahlam/3.png",
    title: "كاكاو",
    price: "8",
    description: "القهوة سريعة التحضير 3 بـ 1",
  },
  {
    id: "2",
    imageUrl: "/products/ahlam-coffee/ahlam/3.png",
    title: "ميسين بوتاني",
    price: "3",
    description: "القهوة سريعة التحضير 3 بـ 1",
  },
  {
    id: "3",
    imageUrl: "/products/ahlam-coffee/ahlam/3.png",
    title: "ميسين قراني",
    price: "3",
    description: "القهوة سريعة التحضير 3 بـ 1",
  },
  {
    id: "4",
    imageUrl: "/products/ahlam-coffee/ahlam/3.png",
    title: "نسكافيه عادي",
    price: "12",
    description: "القهوة سريعة التحضير 3 بـ 1",
  },
  {
    id: "5",
    imageUrl: "/products/ahlam-coffee/ahlam/3.png",
    title: "نسكافيه عبوة",
    price: "7",
  },
  {
    id: "6",
    imageUrl: "/products/ahlam-coffee/ahlam/3.png",
    title: "نسكافيه عبوة عالمي",
    price: "16.67",
  },
  {
    id: "7",
    imageUrl: "/products/ahlam-coffee/ahlam/3.png",
    title: "نسكافيه مصري",
    price: "6",
    description: "القهوة سريعة التحضير 3 بـ 1",
  },
  {
    id: "8",
    imageUrl: "/products/ahlam-coffee/ahlam/3.png",
    title: "كرنولا كبس كاين",
    price: "22",
    description: "القهوة سريعة التحضير 3 بـ 1",
  },
  {
    id: "9",
    imageUrl: "/products/ahlam-coffee/ahlam/3.png",
    title: "كرنولا قهوة فلات",
    price: "2.5",
    description: "القهوة سريعة التحضير 3 بـ 1",
  },
  {
    id: "10",
    imageUrl: "/products/ahlam-coffee/ahlam/3.png",
    title: "دريس قهوة فلات",
    price: "2",
    description: "القهوة سريعة التحضير 3 بـ 1",
  },
  {
    id: "11",
    imageUrl: "/products/ahlam-coffee/ahlam/3.png",
    title: "دريس كبس قهوة نيل",
    price: "20",
    description: "القهوة سريعة التحضير 3 بـ 1",
  },
  {
    id: "12",
    imageUrl: "/products/ahlam-coffee/ahlam/3.png",
    title: "دريس كبس شتاء نعناع",
    price: "22",
    description: "القهوة سريعة التحضير 3 بـ 1",
  },
  {
    id: "13",
    imageUrl: "/products/ahlam-coffee/ahlam/3.png",
    title: "زعتر الاحلام",
    price: "20",
  },
  {
    id: "14",
    imageUrl: "/products/ahlam-coffee/ahlam/3.png",
    title: "اوريو مطريات 3+1",
    price: "24",
  },
  {
    id: "15",
    imageUrl: "/products/ahlam-coffee/ahlam/3.png",
    title: "اوريو 24 مطريات 3+1",
    price: "20",
    description: "القهوة سريعة التحضير 3 بـ 1",
  },
  {
    id: "16",
    imageUrl: "/products/ahlam-coffee/ahlam/3.png",
    title: "نسكافيه غولد 100ج اوريما",
    price: "45",
  },
  {
    id: "17",
    imageUrl: "/products/ahlam-coffee/ahlam/3.png",
    title: "نسكافيه غولد اوريما",
    price: "20.5",
  },
  {
    id: "18",
    imageUrl: "/products/ahlam-coffee/ahlam/3.png",
    title: "نسكافيه اوريكلاسيسك",
    price: "20.5",
    description: "القهوة سريعة التحضير 3 بـ 1",
  },
  {
    id: "19",
    imageUrl: "/products/ahlam-coffee/ahlam/3.png",
    title: "نسكافيه اوريما امل",
    price: "20.5",
  },
  {
    id: "20",
    imageUrl: "/products/ahlam-coffee/ahlam/3.png",
    title: "كاكاولو200ج",
    price: "50",
    description: "القهوة سريعة التحضير 3 بـ 1",
  },
  {
    id: "21",
    imageUrl: "/products/ahlam-coffee/ahlam/3.png",
    title: "جيلي كور ليم",
    price: "14",
    description: "القهوة سريعة التحضير 3 بـ 1",
  },
  {
    id: "22",
    imageUrl: "/products/ahlam-coffee/ahlam/3.png",
    title: "كاستر اوريما",
    price: "11",
    description: "القهوة سريعة التحضير 3 بـ 1",
  },
  {
    id: "23",
    imageUrl: "/products/ahlam-coffee/ahlam/3.png",
    title: "كريمة شيف ايفوريا",
    price: "12",
  },
  {
    id: "24",
    imageUrl: "/products/ahlam-coffee/ahlam/3.png",
    title: "هوه شي كلف ب250ج",
    price: "20",
  },
  {
    id: "25",
    imageUrl: "/products/ahlam-coffee/ahlam/3.png",
    title: "كلوبيندو لوريا",
    price: "2.7",
    description: "القهوة سريعة التحضير 3 بـ 1",
  },
  {
    id: "26",
    imageUrl: "/products/ahlam-coffee/ahlam/3.png",
    title: "كابتشينو الاحلام فلات",
    price: "2.3",
    description: "القهوة سريعة التحضير 3 بـ 1",
  },
  {
    id: "27",
    imageUrl: "/products/ahlam-coffee/ahlam/3.png",
    title: "هوه شو كلف",
    price: "3.75",
    description: "القهوة سريعة التحضير 3 بـ 1",
  },
];
